package Faucet::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Faucet::Schema',
    
    connect_info => {
        dsn => 'dbi:SQLite:faucet.db',
        user => '',
        password => '',
    }
);

=head1 NAME

Faucet::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Faucet>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Faucet::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.59

=head1 AUTHOR

pavel

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
